import turtle
def initials():
    braid=turtle.Turtle()
    window=turtle.Screen()
    window.bgcolor("blue")
    braid.right(90)
    braid.forward(300)
    braid.penup()
    braid.backward(150)
    braid.pendown()
    braid.left(45)
    braid.forward(211.5)
    braid.penup()
    braid.right(45)
    braid.backward(150)
    braid.left(90)
    braid.backward(150)
    braid.pendown()
    braid.left(45)
    braid.forward(211.5)
    braid.penup()
    braid.right(45)
    braid.forward(50)
    braid.pendown()
    braid.right(90)
    braid.forward(300)
    braid.left(90)
    braid.forward(150)
    window.exitonclick()

initials()
